
[ClassVersion("1.0"), FriendlyName("XMLConfigFile")]
class xXMLConfigFile : OMI_BaseResource
{
    [Key, Description("Path to config file")] String ConfigPath;
    [Key, Description("XPath to use")] String XPath;
    [Write, Description("Name of the attribute/element")] String Name;
    [Write, Description("Value of the attribute")] String Value;
    [Write, Description("Name is attribute")] Boolean isAttribute;
    [Write, Description("Name is element only")] Boolean isElementTextValue;
    [Write, Description("Required for key/value pair. Default: key")] String Attribute1;
    [Write, Description("Required for key/value pair. Default: value")] String Attribute2;
    [Write, Description("Whether to create a backup before changing a file")] Boolean DoBackup;
    [Write, Description("Ensure Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Define XmlNamespaceManager. If omitted the resource determines one from file.")] String XMLNS;
    [Write, Description("The prefix of the XmlNamespaceManager, which is used in the XPath")] String NSPrefix;
    [Write, Description("Enforce no XMLNS")] Boolean EnforceNullXMLNS;
};

